@host = http://localhost:5074

###
# Create Auction
POST {{host}}/auctions
Content-Type: application/json

{
    "name": "Pokemon Yellow",
    "auctionPrice": 12500,
    "proxyServiceName": "ZenMarket",
    "wonAt": "2026-07-30"
}

###
# Create Auction
POST {{host}}/auctions
Content-Type: application/json

{
    "name": "Granblue Fantasy Relink: Endless Ragnarok (Sw",
    "auctionPrice": 6200,
    "proxyServiceName": "ZenMarket",
    "wonAt": "2026-08-01"
}

###
# Get All Auctions
GET {{host}}/auctions

###
# Get Auction By Id
GET {{host}}/auctions/4

###
# Update General Info
PUT {{host}}/auctions/4/generalInfo
Content-Type: application/json

{
    "name": "TEST UPDATE",
    "auctionPrice": 13000,
    "proxyServiceName": "ZenMarket",
    "wonAt": "2026-07-30"
}

###
# Verify Update
GET {{host}}/auctions/8

###
# Test Not Found
PUT {{host}}/auctions/999/generalInfo
Content-Type: application/json

{
    "name": "Test",
    "auctionPrice": 100,
    "proxyServiceName": "Test",
    "wonAt": "2026-07-30"
}

###
#Test Update Shipping Info
PUT {{host}}/auctions/8/shipping
Content-Type: application/json

{
    "localShippingCost": 0,
    "internationalShippingMethod": "FedEx",
    "internationalShippingCost": 2000
}

###
#TEST partial update shipping info
PUT {{host}}/auctions/8/shipping
Content-Type: application/json

{
    "localShippingCost": 0
}

###
# Test Not Found Update Shipping Info
PUT {{host}}/auctions/999/shipping
Content-Type: application/json

{
    "localShippingCost": 1500
}

### Test Delete Auction By Id
DELETE {{host}}/auctions/7